COMPILE_DEPS = [
    '//models/common:onos-models-common',
]

APPS = [
    'org.onosproject.models.common',
]

yang_model(
    app_name = 'org.onosproject.models.fpcagent',
    title = 'FPC Agent YANG Models',
    deps = COMPILE_DEPS,
    required_apps = APPS,
)
