COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:KRYO',
    '//lib:onos-yang-model',
    '//lib:httpclient-osgi',
    '//lib:httpcore-osgi',
    '//core/store/serializers:onos-core-serializers',
    '//apps/restconf/utils:onos-apps-restconf-utils',
    '//apps/config:onos-apps-config',
    '//models/fpcagent:onos-models-fpcagent',
    '//models/common:onos-models-common',
    ':zeromq',
    ':json',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//lib:TEST_REST',
    '//utils/osgi:onlab-osgi-tests',
]

BUNDLES = [
    '//apps/fpcagent:onos-apps-fpcagent',
    '//lib:httpclient-osgi',
    '//lib:httpcore-osgi',
]

EXCLUDED_BUNDLES = [
    ':zeromq',
    ':json',
]

APPS = [
    'org.onosproject.models.fpcagent',
    'org.onosproject.yang',
    'org.onosproject.yang-gui',
    'org.onosproject.config',
    'org.onosproject.restconf',
    'org.onosproject.protocols.restconfserver',
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app(
    app_name = 'org.onosproject.fpcagent',
    title = 'YANG FPC Agent',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    description = 'FPC Agent YANG Application',
    required_apps = APPS,
    included_bundles = BUNDLES,
    excluded_bundles = EXCLUDED_BUNDLES,
)

remote_jar (
  name = 'json',
  out = 'json-20090211.jar',
  url = 'mvn:org.json:json:jar:20090211',
  sha1 = 'c183aa3a2a6250293808bba12262c8920ce5a51c',
  maven_coords = 'org.json:json:jar:NON-OSGI:20090211',
  visibility = [ 'PUBLIC' ],
)

remote_jar (
  name = 'zeromq',
  out = 'jeromq-0.3.5.jar',
  url = 'mvn:org.zeromq:jeromq:jar:0.3.5',
  sha1 = '39a79082570d114bb5433762e836e4dd9c38b03d',
  maven_coords = 'org.zeromq:jeromq:0.3.5',
  visibility = [ 'PUBLIC' ],
)
